### ISSUE TITLE
Suggestion: Don't use == comparison for authentication in sample code

### ISSUE THREAD

**Issue by dideler** [mailgun/documentation#133]
In the User Manual, the sample code for verifying the Mailgun authentication signature uses `==`.

E.g. https://github.com/mailgun/documentation/commit/e306a375fb8b3d042865396b58958fa5e2524ba0#diff-229131ed0af7cf80ed3a9470ec7beb4cR701

But [`==` comparisons are vulnerable to timing attacks](http://codahale.com/a-lesson-in-timing-attacks/).
Is it worth mentioning to use a constant time comparison?

In Ruby, there's a `secure_compare` method provided by Rack and Rails.

``` ruby
# Rack
Rack::Utils.secure_compare(a, b)

# Rails
ActiveSupport::SecurityUtils.secure_compare(a, b)
```

In Python, there's a `compare_digest` function in the standard library.

``` python
import hmac
hmac.compare_digest(a, b)
```

Both languages also have 3rd party libraries if the reader doesn't want to use any of the above methods.

**Comment by pirogoeth** [comment]
Hi, I'm working on a collection of these in #217 :)
