### ISSUE TITLE
Suppressions

### ISSUE THREAD

**Issue by levidurfee** [mailgun/documentation#141]
https://documentation.mailgun.com/api-suppressions.html#view-all-bounces

```
limit   Maximum number of records to return (optional, default: 100, max: 10000)
```

I think the limit is 1000, so that should be:

```
limit   Maximum number of records to return (optional, default: 100, max: 1000)
```

**Comment by pirogoeth** [comment]
Actually, it looks like the max limit is 10000 for any requests that will return a batch of entries via `GET` request. The max of 1000 is for submitting a batch of entries via `POST` request.

Corresponding line in [scroll](https://github.com/mailgun/scroll/blob/master/app.go#L22).
