### ISSUE TITLE
Add tutorial for Feedback Loop registration

### ISSUE THREAD

**Issue by jessespears** [mailgun/documentation#145]
Mailgun registers its domains and IP addresses with most ESPs' Feedback Loop programs.

Some ESPs perform Feedback Loop participation by domain, rather than IP address.  We need to have a tutorial to explain what settings are required for these feedback loop programs to allow Mailgun to consume the complaint.

**Comment by nishmith** [comment]
Path.filename(//constructor feed);

**Comment by nishmith** [comment]
Path.filename.feedback.loop(domain name register)

**Comment by jeffturpin1987** [comment]
This is no longer needed as all FBL setup is performed automatically by the Mailgun compliance team.
