### ISSUE TITLE
The curl after sign up success is missing an ending quote

### ISSUE THREAD

**Issue by Ranhiru** [mailgun/documentation#156]
I saw the following curl request after I signed up.

```
curl -s --user 'api:key-BLAH BLAH' \
    https://api.mailgun.net/v3/sandbox-whatever.mailgun.org/messages \
    -F from='Mailgun Sandbox <postmaster@sandboxwhatever.mailgun.org>' \
    -F to='Test Test <test@test.com>'\
    -F subject='Hello Test Test' \
    -F text='Congratulations Test Test, you just sent an email with Mailgun!  You are truly awesome! 
```

However the last line is missing the ending single quote. I can send a pull request but it seems like it's not in this repo.

**Comment by pirogoeth** [comment]
Hey there! I can't seem to find the missing quote in any curl commands in our documentation samples. If you find it, please feel free to reopen this issue.

Thanks!
