### ISSUE TITLE
How to send html emails?

### ISSUE THREAD

**Issue by kevinsimper** [mailgun/documentation#168]
All the examples shows plain text examples, what about showing an simple example with html?

**Comment by otraore** [comment]
What language/library are you using? There are examples showing how to send html.

**Comment by kevinsimper** [comment]
There is very few examples of html emails. I can only count two and they are very small.

**Comment by otraore** [comment]
I think it's because to send html version you only need to add in an extra parameter for existing libraries out there.

For example:
Ruby (Just Text)
```ruby
def send_simple_message
  RestClient.post "https://api:YOUR_API_KEY"\
  "@api.mailgun.net/v3/YOUR_DOMAIN_NAME/messages",
  :from => "Excited User <mailgun@YOUR_DOMAIN_NAME>",
  :to => "bar@example.com, YOU@YOUR_DOMAIN_NAME",
  :subject => "Hello",
  :text => "Testing some Mailgun awesomness!"
end
```
Ruby (Text & HTML)
```ruby
def send_simple_message
  RestClient.post "https://api:YOUR_API_KEY"\
  "@api.mailgun.net/v3/YOUR_DOMAIN_NAME/messages",
  :from => "Excited User <mailgun@YOUR_DOMAIN_NAME>",
  :to => "bar@example.com, YOU@YOUR_DOMAIN_NAME",
  :subject => "Hello",
  :text => "Testing some Mailgun awesomness!",
  :html => "<h1>Testing some Mailgun awesomeness!"
end
```

**Comment by Yaseen-Nadaf** [comment]
I am facing issue with HTML email. I followed the directions given in the documentation. Can someone tell me how to include links in "html" property as it's value is string? Whatever HTML I am writing, it is printed as a string. If I am trying to concatenate strings for "html" property then it is a syntax error as we have to include all html format inside a string.

I am using python language.
