### ISSUE TITLE
jersey 2 examples

### ISSUE THREAD

**Issue by manishpatelUK** [mailgun/documentation#177]
Would be really great to replace the old Jersey 1 examples with Jersey 2. I'd be surprised if any new projects would be on Jersey 1.

**Comment by pirogoeth** [comment]
Hi @manishpatelUK, I've updated the Java docs to use jersey2 in [this](https://github.com/mailgun/documentation/pull/224/files) PR, could you look at them and let me know if they work for you? Thanks!

**Comment by manishpatelUK** [comment]
@pirogoeth Thanks! I only use a fraction of the API (send email, campaign) but looks good to me.

**Comment by pirogoeth** [comment]
Thanks :)

I'm gonna close this ticket now.
