### ISSUE TITLE
Control panel link does not work

### ISSUE THREAD

**Issue by ArtskydJ** [mailgun/documentation#189]
**Issue:** If I click the `Control Panel` link, I'm directed to `https://cp`.
**Expected:** To be redirected to the Control panel, not a broken link.

![1056am](https://cloud.githubusercontent.com/assets/1833684/14466687/7c0d137e-009d-11e6-9701-dba00a2ece14.PNG)

Steps to reproduce the bug:
1. Go to https://documentation.mailgun.com/
2. Click the Control Panel link.

Thanks for the sweet service, mailgun is really cool!

**Comment by pirogoeth** [comment]
Thanks for the report!
