### ISSUE TITLE
Docs missing SMTP header table

### ISSUE THREAD

**Issue by plainlystated** [mailgun/documentation#191]
The docs [1] have a table of SMTP headers in the code, but it is is not rendering for me. 
![screenshot from 2016-05-17 20 25 13](https://cloud.githubusercontent.com/assets/37447/15344585/806b938c-1c6d-11e6-8574-45ddac1257d7.png)

[1] https://github.com/mailgun/documentation/commit/6a6963d8b521b0076d5d02faf859d7e88630a8ac#diff-229131ed0af7cf80ed3a9470ec7beb4cR254

**Comment by pirogoeth** [comment]
@plainlystated It renders on my side. Does the table still not render for you?
