### ISSUE TITLE
"message-url" attribute is not present on stored messages

### ISSUE THREAD

**Issue by kiwiholmberg** [mailgun/documentation#207]
Even tho it's specified in the docs. I think this is some remains for the removed delete functionality.
(https://github.com/mailgun/documentation/commit/fbbf9277e4a21f33549ddc666473a0b0358c4b18)

Docs for "message-url" remains here.
https://documentation.mailgun.com/user_manual.html#storing-and-retrieving-messages

**Comment by pirogoeth** [comment]
Thanks for filing an issue! I'll fix this today :)

**Comment by pirogoeth** [comment]
So, the `message-url` parameter is only present in the payload that is posted to the URL specified by the `notify` parameter. I'll make a note of this in the documentation.
