### ISSUE TITLE
Webhooks timestamp freshness should be absolute

### ISSUE THREAD

**Issue by RBastianini** [mailgun/documentation#235]
In the PHP code example of the [securing webhooks section](https://github.com/mailgun/documentation/blob/4e0cd941a540d7bbaf21c8dc17ac8313755fbdb4/source/user_manual.rst#securing-webhooks), the timestamp freshness is calculated assuming that the receiving server's local time will be greater than the webhook's timestamp value. This might not be true, and therefore arbitrarily future timestamps would be considered for validation instead of immediately discarded.

(See [PR](https://github.com/mailgun/documentation/pull/234))

**Comment by pirogoeth** [comment]
Merged your PR on this, thanks!
