### ISSUE TITLE
True/False or yes/no

### ISSUE THREAD

**Issue by jsbronder** [mailgun/documentation#244]
The documentation for sending booleans uses yes/no while the following examples use True/False.

For example, setting o:tracking
* https://documentation.mailgun.com/api-sending.html#sending
```
o:tracking
    Toggles tracking on a per-message basis, see Tracking Messages for details. Pass yes or no.
```

* https://documentation.mailgun.com/api-sending.html#examples
```
curl -s --user 'api:YOUR_API_KEY' \
    https://api.mailgun.net/v3/YOUR_DOMAIN_NAME/messages \
    -F from='Sender Bob <sbob@YOUR_DOMAIN_NAME>' \
    -F to='alice@example.com' \
    -F subject='Hello' \
    -F text='Testing some Mailgun awesomness!' \
    -F o:tracking=False
```

**Comment by thrawn01** [comment]
All of true, false, yes, no (mixed case) is acceptable. We should update the docs to mention this.
