### ISSUE TITLE
Outdated Java library mentioned on the page

### ISSUE THREAD

**Issue by adis-me** [mailgun/documentation#289]
Hi,

Just wanted to point out that the Java Library version on the [Libraries page](https://documentation.mailgun.com/en/latest/libraries.html#java) is outdated.

I see that all other Java examples are using [Unirest](http://unirest.io/java.html).

**Comment by jeffturpin1987** [comment]
All libraries officially maintained by Mailgun have been updated to be reflected on the most recent Libraries page.
