### ISSUE TITLE
How to get a single event data when message sent?

### ISSUE THREAD

**Issue by rakeshmali** [mailgun/documentation#314]
As I have found the data with following code but it is tacking records from the list in logs..
```
$mgClient = new Mailgun($key);
$domain = "MY_DOMAIN";
$result = $mgClient->get("$domain/log", array('limit' => 5, 'skip' => 0));
```

I want data only of a single event. Like when an email successfully delivered, a delivered webhook url should triggred and the data at this webhook url should be this events only rather then along with other.

So could you please let me know how to get this??

**Comment by thrawn01** [comment]
Use the webhooks api to setup a webhook, this will do as you ask.
