### ISSUE TITLE
Event docs are incomplete / inconsistent

### ISSUE THREAD

**Issue by neokio** [mailgun/documentation#320]
The events section at https://documentation.mailgun.com/en/latest/user_manual.html#events lists **`failed`** as an event, but there is no further reference to that event anywhere (nor for events **`accepted`**, **`rejected`** or **`stored`**).

This same section also does NOT list **`bounced`** or **`dropped`** as events, even though they are listed further below as events.

Confusing!

**Comment by thrawn01** [comment]
You can find info on the event structure here https://documentation.mailgun.com/en/latest/api-events.html?highlight=events#event-structure

I'll make sure `bounced` and `dropped` are added to the list of events.

**Comment by thrawn01** [comment]
After further investigation I understand the confusion. The [webhook (deprecated) ](https://documentation.mailgun.com/en/latest/api-webhooks-deprecated.html?highlight=dropped#drops-parameters) documentation does mention `bounced` and `dropped` event parameters.  Although the documentation there does have a `event = dropped` and `event = bounced` field in the webhook,  those are not the same as `events` returned by the latest version of the webhook api and the events API.

It may be time to completely remove mention of the old deprecated webhook documentation to avoid future confusion. 

I did find some events which are not included in the official documentation, I will add those.
