### ISSUE TITLE
Update/Change the api key placeholder in the curl command examples 

### ISSUE THREAD

**Issue by ivenk** [mailgun/documentation#387]
Some of the quick start examples using curl use confusing and varying placeholders for the api key.

Example from https://documentation.mailgun.com/en/latest/api-intro.html#authentication
`curl --user 'api:key-3ax6xnjp29jd6fds4gc373sgvjxteol0'`

The placeholder for the api key is `key-3ax6xnjp29jd6fds4gc373sgvjxteol0`. This seems really strange to me and it is not consistent with for example https://documentation.mailgun.com/en/latest/quickstart-sending.html#send-via-api. Here the placeholder 'YOUR_API_KEY' is used.
 I feel like replacing this part with just the word `key` or `YOUR_API_KEY` and then adding a line above mentioning that the user should replace the variable key with his api key would be an improvement. 

The result could look similar to the following:
`curl --user 'api:key'`

This placeholder occurs multiple times. I will try and list all cases I found. 

https://help.mailgun.com/hc/en-us/articles/202464990-How-do-I-start-sending-email-
https://documentation.mailgun.com/en/latest/api-intro.html#authentication

**Comment by thrawn01** [comment]
@ivenk Thank you for reporting this!
