### ISSUE TITLE
match_header and match_recipient must be on the same line

### ISSUE THREAD

**Issue by alantrick** [mailgun/documentation#412]
Line 1318 of the user manual (https://github.com/mailgun/documentation/blame/master/source/user_manual.rst#L1318) has the following match pattern over two lines:

```
match_recipient('^(.*)@example.com$') and
match_header("Content-Language", "^(.*)en-US(.*)$")
```

In my testing, and according to mailgun support, this statement has to be on one line, otherwise mailgun will give you the error "invalid syntax (<unknown>, line 1)"

**Comment by thrawn01** [comment]
merged and closed.
