### ISSUE TITLE
Faqs Link broken 

### ISSUE THREAD

**Issue by itsyub** [mailgun/documentation#447]
Link seems broken on this page([FAQ documentation page](https://documentation.mailgun.com/en/latest/faqs.html#how-do-i-track-which-email-a-recipient-has-replied-to))

Broken url : http://blog.mailgun.com/tracking-replies-in-mailgun-or-any-other-email/
Correct url: https://www.mailgun.com/blog/tracking-replies-in-mailgun-or-any-other-email/

**Comment by thrawn01** [comment]
#448
