### ISSUE TITLE
Broken Link in Mailgun Help Page.

### ISSUE THREAD

**Issue by sijusamson** [mailgun/documentation#486]
**Click on the below link.** 

[https://help.mailgun.com/hc/en-us/articles/203380100-Where-Can-I-Find-My-API-Key-and-SMTP-Credentials-#:~:text=What%20Ports%20Does%20Mailgun%20Support,(STARTTLS)%2C%20and%202525.](url)

- Go to "**What Ports Does Mailgun Support?**"

- Now Click on **SMTP** in  "See our **SMTP** documentation in the users manual to learn how to configure the most popular SMTP software and email clients to work with Mailgun".
When we click on the SMTP, it takes you the page, which says **Sorry This page does not exist**. If you are not using it, please remove it, and link the correct page for it.
![Screenshot from 2020-07-08 11-23-16](https://user-images.githubusercontent.com/38852547/86882194-792dc600-c10d-11ea-93b8-0131f1992080.png)

**Comment by jeffturpin1987** [comment]
This has been rectified in a previous release by providing a link to the Control Panel login page instead.
